### ISSUE TITLE
For 60 step one, the resolution is obviously wrong 

### ISSUE THREAD

**Issue by caileiYanxiu** [fogleman/rush#2]
go run cmd/solve/main.go IBBxooIooLDDJAALooJoKEEMFFKooMGGHHHM
{true [L-1 G+1 J+1 D-2 K+1 C-3 K-1 L-2 D+3 K+2 A+2 C+2 J-2 E+1 I+1 H+1 B-1 J-2 A-2 K-1 E+3 K+1 A+2 J+4 B+1 C-2 H-1 A-3 K-2 D-3 E-1 K+1 L+2 C+3 K-1 D+2 J-3 F+1 I+1 D-3 J+2 K+1 C-1 L-1 E+1 K+1 A+3 H+1 B-1 J-3 A-2 D+1 I-1 F-1 G-1 K-1 E-3 K+1 L+2 A+3] 60 103 60 2060 246774}

guess there is a offset one problem.

**Comment by fogleman** [comment]
Looks correct to me. I played it out on the board here and it worked:

https://www.michaelfogleman.com/static/rush/#IBBxooIooLDDJAALooJoKEEMFFKooMGGHHHM/60

**Comment by caileiYanxiu** [comment]
![60](https://user-images.githubusercontent.com/15226131/44500693-7f9f2a00-a6bc-11e8-8c51-74679849ae7b.jpg)

According to :
go run cmd/solve/main.go IBBxooIooLDDJAALooJoKEEMFFKooMGGHHHM
{true [L-1 G+1 J+1 D-2 K+1 C-3 K-1 L-2 D+3 K+2 A+2 C+2 J-2 E+1 I+1 H+1 B-1 J-2 A-2 K-1 E+3 K+1 A+2 J+4 B+1 C-2 H-1 A-3 K-2 D-3 E-1 K+1 L+2 C+3 K-1 D+2 J-3 F+1 I+1 D-3 J+2 K+1 C-1 L-1 E+1 K+1 A+3 H+1 B-1 J-3 A-2 D+1 I-1 F-1 G-1 K-1 E-3 K+1 L+2 A+3] 60 103 60 2060 246774}

The first step is 'L-1', should be 'M-1', second is 'G+1', should be 'H+1'

Sorry, but do I miss something?

**Comment by fogleman** [comment]
I see what's wrong, the labels are getting changed in the code somewhere.

If you run:

`go run cmd/render/main.go IBBxooIooLDDJAALooJoKEEMFFKooMGGHHHM`

With:

```
	showPieceLabels    = true
	showSolution       = true
```

Then you'll see this:

![out](https://user-images.githubusercontent.com/520208/44501041-7af55a00-a659-11e8-8c0e-8ed60bc62d81.png)

**Comment by fogleman** [comment]
It's because the C++ code that generated the puzzle considers the wall as a "piece" so there was no `C` piece. But the Go code re-labels the pieces A-Z.

**Comment by caileiYanxiu** [comment]
ok, got it
BTW, this is really a brilliant project ! Thanks a lot

**Comment by mephitrpg** [comment]
> I see what's wrong, the labels are getting changed in the code somewhere.
> 
> If you run:
> 
> `go run cmd/render/main.go IBBxooIooLDDJAALooJoKEEMFFKooMGGHHHM`
> 
> With:
> 
> ```
> 	showPieceLabels    = true
> 	showSolution       = true
> ```
> 
> Then you'll see this:
> 
> ![out](https://user-images.githubusercontent.com/520208/44501041-7af55a00-a659-11e8-8c0e-8ed60bc62d81.png)

I edited `/render.go` setting `showPieceLabels = true` at line 14 then I launched

```
go run cmd/render/main.go BCCPooBDDPooAAEPooooEFFQGGHoIQJJHoIQ out.png
```

and tried other changes (colors) but it seems it doesn't apply my edits: I can't see letters.

What am I doing wrong? (I don't know Go but I'm a JavaScript senior developer)

**Comment by mephitrpg** [comment]
I fixed it in the editor and viewer of my fork https://github.com/mephitrpg/rush-hour-fogleman-utilities/blob/master/GENERATE-ISSUES.md
